import { isSelfLoop, type IRGraph } from "@/core/ir/types";
import type { LaidOutNode, LayoutResult } from "@/core/layout";
import {
  arrowheadsFor,
  drawShape,
  edgeGeometry,
  labelPosition,
  LABEL_FONT_SIZE,
  measureNode,
  primsToPaths,
  selfLoopGeometry,
  shapeOffset,
  type DrawPath,
  type RenderMode,
} from "@/core/render";
import { archetypeByName } from "@/core/registry";

/**
 * Standalone SVG, generated by the same code that paints the canvas.
 *
 * This is the payoff for keeping `render/` free of React and the DOM: an export
 * is not a second renderer that has to be kept in step, it is the same
 * functions with a different sink. Rough.js seeding makes it exact — the file
 * you download has byte-identical strokes to the diagram you were looking at.
 */

export interface SvgTheme {
  ink: string;
  paper: string;
  background: string;
}

/**
 * Exports resolve CSS variables to literal colours, because a downloaded file
 * has no stylesheet to inherit from.
 */
export const LIGHT_THEME: SvgTheme = {
  ink: "#26262e",
  paper: "#ffffff",
  background: "#f7f7f5",
};

export interface SvgOptions {
  mode: RenderMode;
  padding?: number;
  transparent?: boolean;
  theme?: SvgTheme;
}

const HAND_STACK = "'Architects Daughter', 'Bradley Hand', 'Segoe Print', cursive";
const SANS_STACK =
  "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif";

const round = (n: number) => Math.round(n * 100) / 100;

export function escapeXml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function paintPaths(paths: readonly DrawPath[], theme: SvgTheme, width = 1.6): string {
  return paths
    .map((path) =>
      path.role === "fill"
        ? `<path d="${path.d}" fill="${theme.paper}"/>`
        : `<path d="${path.d}" fill="none" stroke="${theme.ink}" stroke-width="${width}" stroke-linecap="round" stroke-linejoin="round"${
            path.dashed ? ' stroke-dasharray="7 5"' : ""
          }/>`,
    )
    .join("");
}

/**
 * Anchor points must match the canvas exactly, so they are derived the same way
 * React Flow derives them from its handles: out of the right edge, into the
 * left edge, both at mid-height.
 */
function anchors(source: LaidOutNode, target: LaidOutNode) {
  return {
    start: { x: source.x + source.w, y: source.y + source.h / 2 },
    end: { x: target.x, y: target.y + target.h / 2 },
  };
}

function nodeSvg(
  node: LaidOutNode,
  label: string,
  archetype: string,
  mode: RenderMode,
  theme: SvgTheme,
): string {
  const shape = archetypeByName(archetype);
  const box = measureNode(shape, label);
  const offset = shapeOffset(box);
  const paths = drawShape(
    shape.geometry(box.shapeW, box.shapeH),
    mode,
    node.id,
    box.shapeW,
    box.shapeH,
  );
  const text = labelPosition(shape, box);
  const font = mode === "sketch" ? HAND_STACK : SANS_STACK;

  return [
    `<g transform="translate(${round(node.x)} ${round(node.y)})">`,
    `<g transform="translate(${round(offset.x)} ${round(offset.y)})">`,
    paintPaths(paths, theme),
    `</g>`,
    `<text x="${round(text.x)}" y="${round(text.y)}" text-anchor="middle" fill="${theme.ink}" font-size="${LABEL_FONT_SIZE}" font-family="${font}">${escapeXml(label)}</text>`,
    `</g>`,
  ].join("");
}

export function toSVG(
  graph: IRGraph,
  layout: LayoutResult,
  options: SvgOptions,
): string {
  const { mode } = options;
  const theme = options.theme ?? LIGHT_THEME;
  const padding = options.padding ?? 48;
  const titleHeight = graph.title ? 56 : 0;

  const placed = new Map(layout.nodes.map((n) => [n.id, n]));
  const byId = new Map(graph.nodes.map((n) => [n.id, n]));

  // A self-loop arcs above its node, so the canvas extent alone would clip it.
  const loopHeadroom = graph.edges.some(isSelfLoop) ? 90 : 0;
  const topPad = padding + titleHeight + loopHeadroom;

  const width = round(layout.width + padding * 2);
  const height = round(layout.height + topPad + padding);

  const body: string[] = [];

  if (!options.transparent) {
    body.push(
      `<rect x="0" y="0" width="${width}" height="${height}" fill="${theme.background}"/>`,
    );
  }

  if (graph.title) {
    body.push(
      `<text x="${round(width / 2)}" y="${round(padding + 22)}" text-anchor="middle" fill="${theme.ink}" font-size="26" font-family="${mode === "sketch" ? HAND_STACK : SANS_STACK}">${escapeXml(graph.title)}</text>`,
    );
  }

  body.push(`<g transform="translate(${padding} ${topPad})">`);

  // Edges first, so nodes sit on top of the strokes that meet them.
  for (const edge of graph.edges) {
    const source = placed.get(edge.source);
    const target = placed.get(edge.target);
    if (!source || !target) continue;

    const geometry = isSelfLoop(edge)
      ? selfLoopGeometry(source)
      : (({ start, end }) => edgeGeometry(start, end))(anchors(source, target));

    const paths = primsToPaths(
      [
        { k: "path", d: geometry.d, filled: false },
        ...arrowheadsFor(geometry, edge.direction).map((d) => ({
          k: "path" as const,
          d,
          filled: false,
        })),
      ],
      mode,
      edge.id,
    );

    body.push(paintPaths(paths, theme));

    if (edge.label) {
      const font = mode === "sketch" ? HAND_STACK : SANS_STACK;
      body.push(
        `<text x="${round(geometry.mid.x)}" y="${round(geometry.mid.y)}" text-anchor="middle" dominant-baseline="middle" fill="${theme.ink}" font-size="13" font-family="${font}">${escapeXml(edge.label)}</text>`,
      );
    }
  }

  for (const node of layout.nodes) {
    const source = byId.get(node.id);
    if (!source) continue;
    body.push(nodeSvg(node, source.label, source.archetype, mode, theme));
  }

  body.push("</g>");

  return [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">`,
    graph.title ? `<title>${escapeXml(graph.title)}</title>` : "",
    body.join(""),
    "</svg>",
  ].join("");
}
